config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'
  get 'home/about'

  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :instructors, controllers: { registrations: 'instructors/registrations' }
  devise_for :students, controllers: { registrations: 'students/registrations' }

  resources :instructors do
    resources :courses
  end

  get '/admins', to: 'admins#index', as: :admin_root
  get '/students', to: 'students#index', as: :student_root
  get '/instructors', to: 'instructors#index', as: :instructor_root
  get 'admins/instructors', to: 'admins#instructors', as: :admin_instructors
  get 'admins/courses', to: 'admins#courses', as: :admin_courses
  get 'admins/students', to: 'admins#students', as: :admin_students
  get 'courses/enrolled', to: 'courses#enrolled', as: :course_enrolled_students
  get 'courses/enroll', to: 'courses#enroll', as: :course_enroll_students
  resources :courses
  resources :enrolls, only: %i[create destroy]
  resources :students, except: [:show]
end

app/views/admins/courses.html.erb
<%= render 'courses/courses' %>

<div>
  <%= link_to "Add Course", new_course_path, class: 'btn btn-secondary' %>
  <%= link_to 'Back', admin_root_path, class: 'btn btn-dark' %>
</div>

app/views/admins/index.html.erb
<h1 align="center">Welcome to Admin Home Page</h1>
<section class="tiles">
  <div class="container">
    <div class="row">
      <div class="row">
        <div class="col-md-4 col-lg-4">
          <div class="link-tiles">
            <%= link_to 'Instructors', admin_instructors_path %>
          </div>
        </div>

        <div class="col-md-4 col-lg-4">
          <div class="link-tiles">
            <%= link_to 'Students', admin_students_path %>
          </div>
        </div>

        <div class="col-md-4 col-lg-4">
          <div class="link-tiles">
            <%= link_to 'Courses', admin_courses_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admins/instructors.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Department</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.email %></td>
        <td><%= instructor.department %></td>
        <td><%= link_to 'Courses', instructor_courses_url(instructor), class: 'btn btn-outline-primary' %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor), class: 'btn btn-outline-info' %></td>
        <td><%= link_to 'Delete', instructor, method: :delete, data: { turbo_method: :delete,
                                                                       turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<div>
  <%= link_to "New Instructor", new_instructor_path, class: 'btn btn-secondary' %>
  <%= link_to 'Back', admin_root_path, class: 'btn btn-dark' %>
</div>

app/views/admins/students.html.erb
<h2 align="center"><strong>Students</strong></h2>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Student ID</th>
      <th scope="col">Name</th>
      <th scope="col">Date Of Birth</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Major</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.student_id %></td>
        <td><%= student.name %></td>
        <td><%= student.dob %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= student.major %></td>
        <td><%= link_to 'Enroll', student_root_path(id: student.student_id), class: 'btn btn-outline-success' %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-outline-info' %></td>
        <td><%= link_to 'Delete', student, method: :delete,
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                        class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<div>
  <%= link_to "New student", new_student_path, class: 'btn btn-secondary' %>
  <%= link_to 'Back', admin_root_path, class: 'btn btn-dark' %>
</div>