config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'
  get 'home/about'

  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :instructors, controllers: { registrations: 'instructors/registrations' }
  devise_for :students, controllers: { registrations: 'students/registrations' }

  resources :instructors do
    resources :courses
  end

  get '/admins', to: 'admins#index', as: :admin_root
  get '/students', to: 'students#index', as: :student_root
  get '/instructors', to: 'instructors#index', as: :instructor_root
  get 'admins/instructors', to: 'admins#instructors', as: :admin_instructors
  get 'admins/courses', to: 'admins#courses', as: :admin_courses
  get 'admins/students', to: 'admins#students', as: :admin_students
  get 'courses/enrolled', to: 'courses#enrolled', as: :course_enrolled_students
  get 'courses/enroll', to: 'courses#enroll', as: :course_enroll_students
  resources :courses
  resources :enrolls, only: %i[create destroy]
  resources :students, except: [:show]
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }, allow_blank: false
  validates :department, presence: true, length: { minimum: 2 }, allow_blank: false
  has_many :courses, dependent: :destroy
end

app/controllers/instructors/registrations_controller.rb
# frozen_string_literal: true

module Instructors
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[name department email encrypted_password])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: %i[name department email encrypted_password])
    end

    # The path used after sign up.
    def after_sign_up_path_for(resource)
      if admin_signed_in?
        admin_instructors_path
      else
        root_path
      end
    end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end

    def sign_up(resource_name, resource)
      true
    end
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: %i[show edit update destroy]
  before_action :authenticate_instructor!, only: %i[index]
  before_action :authenticate_admin!, except: %i[index]

  def index
    @courses = (Course.where(instructor_id: current_instructor.id) unless current_instructor.id.nil?)
  end

  def show; end

  def new
    @instructor = Instructor.new
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    if @instructor.update(instructor_params)
      redirect_to admin_instructors_url, notice: "Instructor #{@instructor.name} was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    name = @instructor.name
    @instructor.destroy
    redirect_to admin_instructors_url, notice: "Instructor #{name} was successfully removed"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_instructor
    @instructor = Instructor.find(params[:id])
    redirect_to admin_instructors_url, notice: "Instructor with id #{params[:id]} not there!" if @instructor.nil?
  end

  # Only allow a list of trusted parameters through.
  def instructor_params
    params.require(:instructor).permit(:name, :email, :password, :department)
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Edit Instructor Profile</h4>
  </div>
  <div class="card-body">
    <%= form_with(model: @instructor, local: true) do |f| %>
      <%= render "home/error_messages", resource: @instructor %>
      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: 'Name', required: true %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.text_field :department, autofocus: true, class: "form-control", placeholder: 'Department', required: true %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: 'Email', required: true %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: 'btn btn-secondary' %>
        <%= link_to "Back", admin_instructors_path, class: 'btn btn-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/instructors/index.html.erb
<h1 align="center"><strong>Courses</strong></h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Course Code</th>
      <th scope="col">Name</th>
      <th scope="col">Room</th>
      <th scope="col">Days</th>
      <th scope="col">Time</th>
      <th scope="col">Status</th>
      <th scope="col">Capacity</th>
      <th scope="col">Waitlist Capacity</th>
      <th colspan="4"></th>
    </tr>
    </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.code, course %></td>
        <td><%= course.name %></td>
        <td><%= course.room %></td>
        <td><%= course.weekday1 %> <%= course.weekday2 %></td>
        <td><%= course.formatted_start_time %> - <%= course.formatted_end_time %></td>
        <td style="color: lightcoral"><%= course.status %></td>
        <td><%= course.capacity - course.enrolled %> of <%= course.capacity %></td>
        <td><%= course.waitlist_capacity - course.wait_listed %> of <%= course.waitlist_capacity %></td>
        <td><%= link_to 'Enroll', course_enroll_students_path(id: course.code), class: 'btn btn-outline-success' %></td>
        <td><%= link_to 'Enrolled', course_enrolled_students_path(id: course.code), class: 'btn btn-outline-primary' %></td>
        <td><%= link_to 'Edit', edit_course_path(course), class: 'btn btn-outline-info' %></td>
        <td><%= link_to 'Delete', course, method: :delete, data: { turbo_method: :delete,
                                                                   turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<div>
  <%= link_to "Add New Course", new_course_path, class: 'btn btn-secondary' %>
</div>

app/views/instructors/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Add New Instructor</h4>
  </div>
  <div class="card-body">
    <%= form_with(model: @instructor) do |f| %>
      <%= render "home/error_messages", resource: @instructor %>
      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control", placeholder: 'Name' %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.text_field :department, class: "form-control", placeholder: 'Department' %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.text_field :email, class: "form-control", placeholder: 'Email' %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control", placeholder: 'Password' %>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: 'Password Confirmation' %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Add", class: 'btn btn-secondary' %>
        <%= link_to "Back", admin_instructors_path, class: 'btn btn-dark' %>
      </div>
    <% end %>
  </div>
</div>