config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'
  get 'home/about'

  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :instructors, controllers: { registrations: 'instructors/registrations' }
  devise_for :students, controllers: { registrations: 'students/registrations' }

  resources :instructors do
    resources :courses
  end

  get '/admins', to: 'admins#index', as: :admin_root
  get '/students', to: 'students#index', as: :student_root
  get '/instructors', to: 'instructors#index', as: :instructor_root
  get 'admins/instructors', to: 'admins#instructors', as: :admin_instructors
  get 'admins/courses', to: 'admins#courses', as: :admin_courses
  get 'admins/students', to: 'admins#students', as: :admin_students
  get 'courses/enrolled', to: 'courses#enrolled', as: :course_enrolled_students
  get 'courses/enroll', to: 'courses#enroll', as: :course_enroll_students
  resources :courses
  resources :enrolls, only: %i[create destroy]
  resources :students, except: [:show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" style="color: red">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <% if admin_signed_in? %>
      <%= link_to 'Home', admin_root_path, class: 'navbar-brand' %>
    <% elsif instructor_signed_in? %>
      <%= link_to 'Home', instructor_root_path, class: 'navbar-brand' %>
    <% elsif student_signed_in? %>
      <%= link_to 'Home', student_root_path, class: 'navbar-brand' %>
    <% else %>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="nav navbar-nav ms-auto mb-2 mb-lg-0">
        <% if !member_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Admin', new_admin_session_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Instructor', new_instructor_session_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Student', new_student_session_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'About Us', home_about_path, class: 'nav-link' %>
          </li>
        <% else %>
          <% if admin_signed_in? %>
            <li class="nav-item">
              <a class="nav-link active">Role: <u>Admin</u> (<%= current_admin.name %>)</a>
            </li>
            <li class="nav-item">
              <%= link_to "Edit Profile", edit_admin_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete, data: { turbo_method: :delete }, class: 'nav-link' %>
            </li>
          <% elsif instructor_signed_in? %>
            <li class="nav-item">
              <a class="nav-link active">Role: <b><i>Instructor</i></b> (<%= current_instructor.name %>)</a>
            </li>
            <li class="nav-item">
              <%= link_to "Edit Profile", edit_instructor_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_instructor_session_path, method: :delete, data: { turbo_method: :delete }, class: 'nav-link' %>
            </li>
          <% elsif student_signed_in? %>
            <li class="nav-item">
              <a class="nav-link active">Role: <b>Student</b> (<%= current_student.name %>)</a>
            </li>
            <li class="nav-item">
              <%= link_to "Edit Profile", edit_student_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_student_session_path, method: :delete, data: { turbo_method: :delete }, class: 'nav-link' %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<h1 align="center">Welcome to Student Enrollment Application</h1>
<p>There are three different type of users i.e. Admin, Instructor and Student</p>
<p>All the users have their <b>own login and signup</b> page, select the user from the header on top as per your role.
</p>