config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'
  get 'home/about'

  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :instructors, controllers: { registrations: 'instructors/registrations' }
  devise_for :students, controllers: { registrations: 'students/registrations' }

  resources :instructors do
    resources :courses
  end

  get '/admins', to: 'admins#index', as: :admin_root
  get '/students', to: 'students#index', as: :student_root
  get '/instructors', to: 'instructors#index', as: :instructor_root
  get 'admins/instructors', to: 'admins#instructors', as: :admin_instructors
  get 'admins/courses', to: 'admins#courses', as: :admin_courses
  get 'admins/students', to: 'admins#students', as: :admin_students
  get 'courses/enrolled', to: 'courses#enrolled', as: :course_enrolled_students
  get 'courses/enroll', to: 'courses#enroll', as: :course_enroll_students
  resources :courses
  resources :enrolls, only: %i[create destroy]
  resources :students, except: [:show]
end

app/controllers/courses_controller.rb
# frozen_string_literal: true
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy enrolled enroll]
  before_action :authenticate_instructor?, except: [:show]

  # GET /courses
  def index
    @courses = if !current_instructor.nil?
                 Course.where(instructor_id: current_instructor.id)
               elsif !params[:instructor_id].nil?
                 Course.where(instructor_id: params[:instructor_id])
               else
                 Course.all
               end
  end

  def enrolled
    course_enrolled_students = Enroll.where(course_id: params[:id], waitlist: false).pluck(:student_id)
    course_wait_listed_students = Enroll.where(course_id: params[:id], waitlist: true).pluck(:student_id)
    @enrolled_students = Student.where(student_id: course_enrolled_students)
    @wait_listed_students = Student.where(student_id: course_wait_listed_students)
  end

  def enroll
    course_enrolled_students = Enroll.where(course_id: params[:id]).pluck(:student_id)
    @students = Student.where.not(student_id: course_enrolled_students)
  end

  # GET /courses/1
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
    @instructor = current_instructor
    @instructors = Instructor.all
  end

  # GET /courses/1/edit
  def edit
    if current_instructor && @course.instructor != current_instructor
      redirect_to courses_url, notice: "You are not authorised to edit course #{params[:id]}!"
    end
    @instructor = current_instructor
    @instructors = Instructor.all
  end

  # POST /courses
  def create
    @course = Course.new(course_params)
    @course.instructor = current_instructor unless current_instructor.nil?
    @course[:instructor_name] = Instructor.find(@course.instructor_id).name
    # @course[:instructor_id] = Instructor.where(name: @course.instructor_name).get_primary_key(:id)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      @instructor = current_instructor
      @instructors = Instructor.all
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      @instructor = current_instructor
      @instructors = Instructor.all
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private

  def authenticate_instructor?
    admin_signed_in? || authenticate_instructor!
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find_by_code(params[:id])
    redirect_to courses_url, notice: "Course #{params[:id]} not there!" if @course.nil?
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:name, :description, :instructor_name, :weekday1, :weekday2, :start_time, :end_time,
                                   :code, :capacity, :waitlist_capacity, :status, :room, :instructor_id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courses.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Course Code</th>
      <th scope="col">Name</th>
      <th scope="col">Room</th>
      <th scope="col">Days</th>
      <th scope="col">Time</th>
      <th scope="col">Instructor</th>
      <th scope="col">Status</th>
      <th scope="col">Capacity</th>
      <th scope="col">Waitlist Capacity</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.code, course %></td>
        <td><%= course.name %></td>
        <td><%= course.room %></td>
        <td><%= course.weekday1 %> <%= course.weekday2 %></td>
        <td><%= course.formatted_start_time %> - <%= course.formatted_end_time %></td>
        <td><%= course.instructor_name %></td>
        <td style="color: lightcoral"><%= course.status %></td>
        <td><%= course.capacity - course.enrolled %> of <%= course.capacity %></td>
        <td><%= course.waitlist_capacity - course.wait_listed %> of <%= course.waitlist_capacity %></td>
        <td><%= link_to 'Edit', edit_course_path(course), class: 'btn btn-outline-primary' %></td>
        <td><%= link_to 'Delete', course, method: :delete, data: { turbo_method: :delete,
                                                                   turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <%= render "home/error_messages", resource: course %>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.text_field :code, class:"form-control", placeholder:'Course Code', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.text_field :name, class:"form-control", placeholder:'Name', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.text_field :description, class: "form-control", placeholder: 'Description', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <% options = %w[MON TUE WED THU FRI] %>
      <%= form.select :weekday1, options, { include_blank: "Weekday 1" }, class: "form-select", required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <% options = %w[MON TUE WED THU FRI] %>
      <%= form.select :weekday2, options, { include_blank: "Weekday 2" }, class: "form-select" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.label :start_time %>
      <%= form.time_field :start_time, class: "form-control", placeholder: 'Start Time', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.label :end_time %>
      <%= form.time_field :end_time, class:"form-control", placeholder:'End Time', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.text_field :room, class:"form-control", placeholder:'Room', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.number_field :capacity, class:"form-control", placeholder:'Capacity', required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-6">
      <%= form.number_field :waitlist_capacity, class: "form-control", placeholder: 'Waitlist Capacity', required: true %>
    </div>
  </div>

  <% if admin_signed_in? %>
    <div class="row mb-3">
      <div class="col-sm-6">
        <% options = options_from_collection_for_select(@instructors, 'id', 'name', selected = @course.instructor_id) %>
        <%= form.select :instructor_id, options, { include_blank: "Instructor" }, class: "form-select", required: true %>
      </div>
    </div>
  <% else %>
    <div class="row mb-3">
      <div class="col-sm-6">
        <%= form.text_field :instructor_name, class: "form-control", placeholder: 'Instructor', value: @instructor.name, hidden: true %>
      </div>
    </div>
  <% end %>
  <%= form.submit class: 'btn btn-secondary' %>
<% end %>

app/views/courses/_links.html.erb
<% if admin_signed_in? %>
  <%= link_to "Back", admin_courses_path, class: 'btn btn-dark' %>
<% elsif instructor_signed_in? %>
  <%= link_to "Back", instructor_root_path,class:'btn btn-dark' %>
<% elsif student_signed_in?%>
  <%= link_to "Back", student_root_path, class:'btn btn-dark' %>
<% else %>
  <%= link_to "Back", courses_path, class:'btn btn-dark' %>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>
<%= render "form", course: @course %>
<br>
<div>
  <%= link_to "Back", :back, class: 'btn btn-dark' %>
</div>

app/views/courses/enroll.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Student ID</th>
      <th scope="col">Name</th>
      <th scope="col">Date Of Birth</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Major</th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.student_id %></td>
        <td><%= student.name %></td>
        <td><%= student.dob %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= student.major %></td>
        <td><%= button_to 'Enroll', enrolls_path(student_id: student.id, course_id: @course.code),
                          method: :post, class: 'btn btn-outline-success' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'Back', instructor_root_path, class: 'btn btn-dark' %>

app/views/courses/enrolled.html.erb
<h2 align="center">Enrolled Students- <%= @course.code %></h2>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Student ID</th>
      <th scope="col">Name</th>
      <th scope="col">Date Of Birth</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Major</th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <% @enrolled_students.each do |student| %>
      <tr>
        <td><%= student.student_id %></td>
        <td><%= student.name %></td>
        <td><%= student.dob %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= student.major %></td>
        <td><%= link_to 'Drop', Enroll.where(:student_id => student.student_id, :course_id => @course.code).first, method: :delete,
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<h2 align="center">Wait Listed Students</h2>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover align-middle">
    <thead class="table-dark">
    <tr>
      <th scope="col">Student ID</th>
      <th scope="col">Name</th>
      <th scope="col">Date Of Birth</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Major</th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <% @wait_listed_students.each do |student| %>
      <tr>
        <td><%= student.student_id %></td>
        <td><%= student.name %></td>
        <td><%= student.dob %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= student.major %></td>
        <td><%= link_to 'Drop', Enroll.where(:student_id => student.student_id, :course_id => @course.code).first, method: :delete,
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= link_to 'Enroll Student', course_enroll_students_path(id: @course.code), class: 'btn btn-primary' %>
  <%= link_to 'Back', instructor_root_path, class: 'btn btn-dark' %>
</div>

app/views/courses/index.html.erb
<h1><strong>Courses</strong></h1>
<%= render 'courses/courses' %>
<%= link_to "New course", new_course_path, class:'btn btn-secondary'%>

app/views/courses/new.html.erb
<h2>New course</h2>
<%= render "form", course: @course %>
<br>
<%= render "courses/links" %>

app/views/courses/show.html.erb
<div class="card" style="width: 24rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @course.code %> | <%= @course.name %></h5>
    <p class="card-text"><%= @course.description %></p>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Instructor:</strong> <%= @course.instructor_name %></li>
    <li class="list-group-item"><strong>Room:</strong> <%= @course.room %></li>
    <li class="list-group-item"><strong>Schedule:</strong> <%= @course.formatted_start_time %>
      - <%= @course.formatted_end_time %>,
      <%= @course.weekday1 %> <%= @course.weekday2 %></li>
    <li class="list-group-item"><strong>Status:</strong> <%= @course.status %></li>
    <li class="list-group-item"><strong>Available Seats:</strong> <%= @course.capacity - @course.enrolled %>
      Of <%= @course.capacity %></li>
    <li class="list-group-item">
      <strong>WaitList Capacity:</strong> <%= @course.waitlist_capacity - @course.wait_listed %>
      Of <%= @course.waitlist_capacity %></li>
  </ul>

  <div class="card-body">
    <%= render "courses/links" %>
  </div>
</div>